'use client';
import { useEffect, useState } from 'react';
import { adminFetch, adminPatch } from '../lib/adminApi';
import type { AdminIdentity, Feedback, FeedbackCategory, FeedbackStatus, ListResponse, Pagination } from '../lib/contracts';
import styles from '../admin.module.scss';
const statuses: Array<'' | FeedbackStatus> = ['', 'open', 'in_progress', 'resolved']; const categories: Array<'' | FeedbackCategory> = ['', 'bug', 'experience', 'feature', 'billing', 'other'];
type Filters = { status: string; category: string; userId: string; assignedToSelf: boolean; from: string; to: string; page: number }; const initial: Filters = { status: '', category: '', userId: '', assignedToSelf: false, from: '', to: '', page: 1 }; const emptyPage: Pagination = { page: 1, limit: 20, total: 0, hasNext: false };
export default function FeedbackPage() {
 const [draft,setDraft]=useState(initial); const [filters,setFilters]=useState(initial); const [result,setResult]=useState<ListResponse<Feedback>>({items:[],pagination:emptyPage}); const [admin,setAdmin]=useState<AdminIdentity|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [pending,setPending]=useState<string|null>(null);
async function load(next: Filters=filters){setLoading(true);setError('');const p=new URLSearchParams({page:String(next.page),limit:'20'});Object.entries(next).forEach(([k,v])=>{if(k!=='page'&&v)p.set(k,String(v));});try{const [r,m]=await Promise.all([adminFetch<ListResponse<Feedback>>(`/api/admin/feedback?${p}`),adminFetch<{admin:AdminIdentity}>('/api/admin/auth/me')]);setResult({items:r.items??[],pagination:r.pagination??emptyPage});setAdmin(m.admin);}catch(e:unknown){setError(e instanceof Error?e.message:'加载失败');}finally{setLoading(false);}}
 useEffect(()=>{void load(initial);},[]); const items=result.items??[]; const pagination=result.pagination??emptyPage; const writable=admin?.role!=='viewer'&&admin!==null;
 async function update(item:Feedback,body:{status?:FeedbackStatus;assignedToSelf?:boolean;internalNote?:string}){setPending(item.id);setError('');try{await adminPatch(`/api/admin/feedback/${item.id}`,body);await load();}catch(e:unknown){setError(e instanceof Error?e.message:'更新失败');}finally{setPending(null);}}
 return <section><h2>用户反馈</h2><div className={styles.toolbar}><select aria-label="反馈状态筛选" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{statuses.map(s=><option key={s} value={s}>{s||'全部状态'}</option>)}</select><select aria-label="反馈分类筛选" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(s=><option key={s} value={s}>{s||'全部分类'}</option>)}</select><input aria-label="反馈用户筛选" value={draft.userId} onChange={e=>setDraft({...draft,userId:e.target.value})} placeholder="用户 ID"/><label>从 <input aria-label="反馈开始日期" type="date" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>至 <input aria-label="反馈结束日期" type="date" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></label><label><input type="checkbox" checked={draft.assignedToSelf} onChange={e=>setDraft({...draft,assignedToSelf:e.target.checked})}/>只看分配给我</label><button onClick={()=>{const n={...draft,page:1};setFilters(n);void load(n);}}>筛选</button></div>{loading&&<p>加载反馈中…</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}<table className={styles.table}><thead><tr><th>时间</th><th>分类</th><th>状态</th><th>内容</th><th>内部备注</th>{writable&&<th>操作</th>}</tr></thead><tbody>{result.items.map(item=><tr key={item.id}><td>{new Date(item.createdAt).toLocaleString('zh-CN')}</td><td>{item.category}</td><td>{item.status}</td><td>{item.content}</td><td>{item.internalNote||'—'}</td>{writable&&<td><button disabled={pending===item.id} onClick={()=>void update(item,{status:item.status==='open'?'in_progress':'resolved'})}>{pending===item.id?'更新中…':'更新'}</button><button disabled={pending===item.id} onClick={()=>void update(item,{assignedToSelf:!item.assignedTo})}>{item.assignedTo?'取消分配':'分配给我'}</button></td>}</tr>)}</tbody></table>{!loading&&!result.items.length&&!error&&<p className={styles.muted}>暂无反馈</p>}<div className={styles.toolbar}><span>第 {result.pagination.page} 页 · 共 {result.pagination.total} 条</span><button disabled={result.pagination.page<=1||loading} onClick={()=>{const n={...filters,page:filters.page-1};setFilters(n);void load(n);}}>上一页</button><button disabled={!result.pagination.hasNext||loading} onClick={()=>{const n={...filters,page:filters.page+1};setFilters(n);void load(n);}}>下一页</button></div></section>;
}
