'use client';
import { useEffect, useState } from 'react';
import { adminFetch } from '../lib/adminApi';
import type { AdminUser } from '../lib/contracts';
import styles from '../admin.module.scss';

export default function UsersPage() {
  const [draft,setDraft]=useState(''); const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [page,setPage]=useState(1); const [result,setResult]=useState<{items:AdminUser[];pagination:{page:number;limit:number;total:number;hasNext:boolean}}>({items:[],pagination:{page:1,limit:20,total:0,hasNext:false}}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{void load(1,'','',from,to)},[]);
  async function load(nextPage=page,nextQuery=query,nextStatus=status,nextFrom=from,nextTo=to){setLoading(true);setError('');const params=new URLSearchParams({page:String(nextPage),limit:'20'});if(nextQuery)params.set('query',nextQuery);if(nextStatus)params.set('status',nextStatus);if(nextFrom)params.set('createdFrom',nextFrom);if(nextTo)params.set('createdTo',nextTo);try{setResult(await adminFetch<typeof result>(`/api/admin/users?${params}`))}catch(e:unknown){setError(e instanceof Error?e.message:'加载失败')}finally{setLoading(false)}}
  return <section><h2>用户管理</h2><div className={styles.toolbar}><input aria-label="搜索用户" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="邮箱或用户名"/><select aria-label="用户状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option value="active">正常</option><option value="disabled">已禁用</option></select><label>从 <input aria-label="用户创建开始日期" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>至 <input aria-label="用户创建结束日期" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setQuery(draft);setPage(1);void load(1,draft,status,from,to)}}>搜索</button></div>{loading&&<p>加载用户中…</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}<table className={styles.table}><thead><tr><th>用户名</th><th>邮箱</th><th>状态</th><th>笔记</th><th>AI 调用</th></tr></thead><tbody>{result.items.map(u=><tr key={u.id}><td><a href={`/admin/users/${u.id}`}>{u.username}</a></td><td>{u.maskedEmail}</td><td>{u.isActive?'正常':'已禁用'}</td><td>{u.noteCount}</td><td>{u.aiCalls30d}</td></tr>)}</tbody></table>{!loading&&!result.items.length&&!error&&<p className={styles.muted}>暂无用户</p>}<div className={styles.toolbar}><span>第 {page} 页 · 共 {result.pagination.total} 条</span><button disabled={page<=1||loading} onClick={()=>{const p=page-1;setPage(p);void load(p)}}>上一页</button><button disabled={!result.pagination.hasNext||loading} onClick={()=>{const p=page+1;setPage(p);void load(p)}}>下一页</button></div></section>;
}
