import express from 'express';
import { asyncHandler, ErrorHandler, ResponseHandler } from '../../utils/errorHandler';
import { requireAdmin, requireAdminMutationOrigin, requireAdminPermission } from '../../middleware/adminAuth';
import { getAiUsage, listFailedArtifacts, retryFailedArtifact } from '../../services/admin/adminAiService';
import { runAuditedAdminCommand } from '../../services/admin/adminAuditService';
const router = express.Router();
router.use(requireAdmin, requireAdminPermission('ai:read'));
router.get('/usage', asyncHandler(async (req, res) => { const range = req.query.range === '30d' ? '30d' : req.query.range === '7d' || req.query.range === undefined ? '7d' : null; if (!range) throw ErrorHandler.createValidationError('range must be 7d or 30d'); ResponseHandler.success(res, await getAiUsage({ range })); }));
router.get('/failures', asyncHandler(async (req, res) => ResponseHandler.success(res, await listFailedArtifacts({ page: Number(req.query.page ?? 1), limit: Number(req.query.limit ?? 20) }))));
router.post('/retry', requireAdminPermission('ai:retry'), requireAdminMutationOrigin, asyncHandler(async (req, res) => { const body = req.body ?? {}; const result = await runAuditedAdminCommand({ actorId: req.admin!.id, requestId: req.requestId, action: 'ai.artifact_retry', targetType: 'Note', targetId: body.noteId, metadata: { reason: typeof body.reason === 'string' ? body.reason.trim() : '', sourceRevision: Number(body.expectedRevision) } }, () => retryFailedArtifact(body)); ResponseHandler.success(res, result); }));
export default router;
