import express from 'express';
import authRoutes from './auth';
import { adminNoStore } from '../../middleware/adminAuth';
import overviewRoutes from './overview';
import systemRoutes from './system';
import userRoutes from './users';
import auditRoutes from './audit';
import feedbackRoutes from './feedback';
import aiRoutes from './ai';
const router = express.Router();
router.use(adminNoStore);
router.use('/auth', authRoutes);
router.use('/overview', overviewRoutes);
router.use('/system', systemRoutes);
router.use('/users', userRoutes);
router.use('/audit', auditRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/ai', aiRoutes);
export default router;
